# Generated by Django 3.0 on 2021-05-27 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210527_0509'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripe_hook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='card_number',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('payment_method', models.CharField(choices=[['ESEWA', 'ESEWA'], ['STRIPE', 'STRIPE']], default='ESEWA', max_length=10)),
                ('full_name', models.CharField(default='John Doe', max_length=200)),
                ('phone_number', models.IntegerField(default=0)),
                ('email', models.EmailField(default='test@gmail.com', max_length=254)),
                ('delivery_address', models.CharField(default='Street Address', max_length=200)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Order')),
            ],
        ),
    ]
