# Generated by Django 3.0 on 2021-05-27 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210527_0509'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripe_hook', '0002_auto_20210527_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='payment_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stripe_hook.Payments'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payments',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_order', to='store.Order'),
        ),
    ]
