# Generated by Django 3.0 on 2021-05-27 05:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210527_0509'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripe_hook', '0003_auto_20210527_0529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='StripePayments',
        ),
    ]
