# Generated by Django 3.0 on 2021-05-27 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210527_0509'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripe_hook', '0004_auto_20210527_0536'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('payment_method', models.CharField(choices=[['STRIPE', 'STRIPE']], default='ESEWA', max_length=10)),
                ('card_number', models.CharField(default='none', max_length=200)),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_customer', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_order', to='store.Order')),
            ],
        ),
        migrations.RenameModel(
            old_name='OrderInfo',
            new_name='StripeOrderInfo',
        ),
        migrations.DeleteModel(
            name='StripePayments',
        ),
        migrations.AlterField(
            model_name='stripeorderinfo',
            name='payment_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stripe_hook.StripePayment'),
        ),
    ]
