# Generated by Django 3.0 on 2021-05-30 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_hook', '0005_auto_20210527_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripepayment',
            name='customer',
        ),
    ]
