# Generated by Django 3.0 on 2021-06-14 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_hook', '0006_remove_stripepayment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeorderinfo',
            name='payment_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_payment_object', to='stripe_hook.StripePayment'),
        ),
        migrations.AlterField(
            model_name='stripepayment',
            name='card_number',
            field=models.CharField(max_length=200),
        ),
    ]
